name: Deploy using Maven

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Publish to GitHub Packages
        run: ./mvnw --batch-mode deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# ??  ./mvnw --batch-mode -DuseGitHubPackages=true deploy --file pom.xml
